bourinnguオブジェクト指向
mame0124/ruby-practices pull request #9
Opened 2022-11-19 06:56 UTC by mame0124

2022-11-19 07:00 UTC, mame0124 commented
ボウリングプログラムをオブジェクト指向に書き換えました！
レビューをお願い致します🙇‍♀️

2022-11-24 13:58 UTC, betachelsea reviewed
提出ありがとうございます！ コメントしました〜 📝

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/shot.rb
> +  end
[MUST] Shot が持っているのが `X` かどうかだけでは、ストライクの判断は難しいはずなので、命名としては違和感あるかなと思いました〜 :eyes:   
- 1投目が `X` → これはストライク
- 1投目が `0` 、2投目が `X` → これはスペア

ストライクの判断をどのclassにさせるか、再考してみていただきたいです！ 🙏

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/frame.rb
> +    self
[MUST] selfを返すのは呼び出し元に影響されてしまっている実装だなと思いました :eyes: 

```ruby
@all_frames[-1] = if @all_frames[-1].first_shot.strike? # ...
```

呼び出し元で `@all_frames[-1]` に対して戻したいために、selfを返しているようですが、
`@all_frames[-1].add_one_shot(...)` を呼び出した時点で、 `@all_frames[-1]` 自体が変更されています。
なので、selfで戻す実装はしなくても大丈夫そうです！試してみてください〜 🙏

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/frame.rb
> +    !@first_shot.strike? && @first_shot.score + @second_shot.score == 10
[nits] 10 は特に意味のある数字のようですね。マジックナンバーの状態になっているので、定数化されてると良いなと思いました 〜 :eyes:

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/game.rb
> +    10.times do
[nits] 小ワザですが、次のように書けそうですね。

```ruby
# 要素数10個の配列をFrameの戻り値で埋めてつくる
@all_frames = 10.times.map do
  shot = Shot.new(all_shots.shift)
  if ...
    Frame.new(shot)
  else
    Frame.new(...)
  end
end


```

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/game.rb
> +    frames[2].first_shot.score
[IMO] うーん、このサイズ感の処理ならそのまま呼び出すのもありなような、命名していることで意図がハッキリするからよいような…。このあたりはレビュアーの好みによって意見が別れそうです :eyes: 

- メソッド化するメリット: 命名によって使い所がわかる
- デメリット: 具体的にframesからどんな値を取り出しているのかはメソッドの中身を参照しにこないとわからない、メソッド名が実際の処理よりも長く書く必要がある状態

2022-11-24 13:58 UTC, betachelsea commented on 07.bowling_object/game.rb
> +  def add_point_for_strike(frames)
[IMO] 解釈によりますが、特に足す処理はしておらず、足すにふさわしい値を計算して出しているのですね。`add_` の表現が必要かどうかは、少し悩ましいなと思いました 🤔  (メソッドの中で最終的な得点に合計する処理をしているわけではない)

2022-12-12 00:45 UTC, mame0124 commented
レビュー頂きありがとうございました🙇‍♀️
修正しましたので、お時間のある時にでも再度ご確認をお願い致します🙏

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/frame.rb
> +    !@first_shot.strike? && @first_shot.score + @second_shot.score == 10
いつも定数化を忘れてしまうので気をつけたいです😵
修正しました！

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/game.rb
> +    10.times do
小ワザありがとうございます！
こんな書き方もできるんですね✨
rubocopを通す為、Array.new(10) doとなりましたが、配列の初期化は無くなり分かりやすくなりました！

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/game.rb
> +  def add_point_for_strike(frames)
誤解を招く命名でした🙏
add_pointの部分をaddition_scoreとしてみました！
もっと良い命名があればアドバイス頂けるとありがたいです🙏

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/shot.rb
> +  end
> 1投目が 0 、2投目が X → これはスペア

このパターンを把握していませんでした😵

ストライクの判断をFrameクラスにさせる様修正しました！

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/frame.rb
> +    self
アドバイスありがとうございます🙏
まわりくどいやり方をしていた事に気づけました！
self返すのをやめ、呼び出し元のGameクラスのコードも修正しました。

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/game.rb
> +    frames[2].first_shot.score
アドバイスありがとうございます🙏
書き換えてみると、コードを読む時にメソッドを探してどんな処理をしているのかを確認する手間がなく、読みやすかったです！
メソッドを削除して、そのまま呼び出す処理に修正しました！

2022-12-12 01:00 UTC, mame0124 commented on 07.bowling_object/game.rb
> +  def add_point_for_strike(frames)
メソッド名を変更しましたが、メソッドに切り出さない方が読みやすい様だったので、メソッドを削除しました！

2022-12-13 15:13 UTC, betachelsea requested changes
修正ありがとうございます！ 
実行してみたのですが、もしかしてちょっと結果が変になってしまっているかも？

```console
$ruby score_calculation.rb 6,3,9,0,0,3,8,2,7,3,X,9,1,8,0,X,6,4,5
71
```

※↑正解の数値は「139」
一度ご確認いただきたいです！よろしくお願いします 🙏

2022-12-13 15:13 UTC, betachelsea commented on 07.bowling_object/shot.rb
> +    return 10 if @mark == 'X'
[IMO] ここの `10` や `'X'` も定数として扱ってもよさそうな数字だなと思いました〜 :eyes: (好みによりますが！)
[nits] 三項演算子(条件演算子)にしてもスッキリしそうですね。

```ruby
@mark == 'X' ? 10 : @mark.to_i
```

2022-12-13 23:58 UTC, mame0124 commented on 07.bowling_object/shot.rb
> +    return 10 if @mark == 'X'
三項演算子にしてみたらすごくスッキリしました🙌
10とXも定数にしてみました！
アドバイスありがとうございます🙏

2022-12-14 00:05 UTC, mame0124 commented
きちんと動かない状態での提出大変失礼しました！🙇‍♀️
`+`が入るべき所に入っていませんでした🙏
そちらの修正と、アドバイス頂いた点の修正を致しました。
また、タイトルも修正しましたので、お手数おかけしますが、再度ご確認をお願い致します🙇‍♀️

2022-12-14 22:20 UTC, betachelsea approved these changes
修正ありがとうございます！確認OKです 👍

2022-12-14 22:20 UTC, betachelsea commented on 07.bowling_object/game.rb
> +      @all_frames[-1].add_second_and_third_shots(Shot.new(all_shots.shift), Shot.new(all_shots.shift))
[IMO] `add_second_and_third_shots` を呼び出しているのがこの行だけなので、ここは

```ruby
@all_frames[-1].add_second_shot(Shot.new(all_shots.shift))
@all_frames[-1].add_third_shot(Shot.new(all_shots.shift))
```

とそれぞれ呼び出す対応にすると、メンテする Frame クラスのメソッドが減らせそうだなと思いました :eyes:

2023-01-01 00:54 UTC, mame0124 commented on 07.bowling_object/game.rb
> +      @all_frames[-1].add_second_and_third_shots(Shot.new(all_shots.shift), Shot.new(all_shots.shift))
アドバイスありがとうございます！
既にあるメソッドで代用出来たんですね😵
勉強になりました🙏

2023-01-01 00:54 UTC, merged